version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: perdy/circleci-python-builder
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ checksum "Dockerfile" }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/caches/docker.tar
      - run:
          name: Build Docker image
          command: builder build -t app --cache ~/caches/docker.tar
      - save_cache:
          key: v1-{{ checksum "Dockerfile" }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/caches/docker.tar
      - deploy:
          name: Push application Docker image
          command: |
            echo $DOCKER_PASSWORD | base64 -d | docker login -u `echo $DOCKER_USERNAME | base64 -d` --password-stdin
            export SIA_VERSION=`awk '$2=="SIA_VERSION" {print $3}' Dockerfile`
            export DOCKER_IMAGE=`echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${SIA_VERSION}" | awk '{print tolower($0)}'`
            docker tag app $DOCKER_IMAGE
            builder push --tag $DOCKER_IMAGE
  sia:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/
    steps:
      - run:
          name: Get Sia from the master branch
          command: go get -u gitlab.com/NebulousLabs/Sia/...
      - persist_to_workspace:
          root: bin
          paths:
            - siac
            - siad
  sia-debug:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/gitlab.com/NebulousLabs/Sia
    steps:
      - run:
          name: Checking out the debug branch
          command: |
            git clone https://github.com/jkawamoto/Sia.git .
            git checkout -b debug origin/develop
      - run:
          name: Compile Sia
          command: |
            make dependencies
            make release
      - persist_to_workspace:
          root: /go/bin
          paths:
            - siac
            - siad
  dev-build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Docker image
          command: docker build -f Dockerfile.dev -t ${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME}:dev .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | base64 -d | docker login -u `echo $DOCKER_USERNAME | base64 -d` --password-stdin
            docker push ${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME}:dev
  debug-build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Docker image
          command: docker build -f Dockerfile.dev -t ${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME}:debug .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | base64 -d | docker login -u `echo $DOCKER_USERNAME | base64 -d` --password-stdin
            docker push ${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME}:debug
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      # - sia
      # - dev-build:
      #     requires:
      #       - sia
      - sia-debug
      - debug-build:
          requires:
            - sia-debug
